# Single image for the whole NSW Agency service: builds the frontend, ships it
# next to the Go binary, and serves both the API and the SPA from one process.
# This is the ONLY Dockerfile — backend/ and frontend/ no longer build separately.
#
# Build context is the repo ROOT (so both backend/ and frontend/ are reachable):
#   docker build -t agency .
#
# Runtime config (/runtime-env.js, window.__APP_CONFIG__) is generated by the Go
# server per request from the environment — no entrypoint script, no file is
# written at runtime.

# BUILD_VERSION is passed by CI (git tag for releases, dev-<run>-<sha> for dev
# builds — see .github/workflows/release.yml and build-dev.yml) and baked into
# both the frontend bundle and the Go binaries below. Defaults to "dev" for
# local/unversioned builds.
ARG BUILD_VERSION=dev

# ---- Stage 1: build the frontend SPA -----------------------------------------
FROM node:22-bookworm-slim AS frontend-builder

ARG BUILD_VERSION
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

COPY frontend/ .

# Vite only exposes VITE_-prefixed env vars to client code (import.meta.env),
# baking the value into the static bundle at build time.
ENV VITE_APP_VERSION=$BUILD_VERSION
RUN pnpm build

# ---- Stage 2: build the Go binaries ------------------------------------------
FROM golang:1.26.4-bookworm AS backend-builder

ARG BUILD_VERSION
WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

# -ldflags="-s -w" strips the symbol table and DWARF debug info to shrink the
# binaries. Go panic traces (function + line) and pprof still work, since they
# use the runtime pclntab rather than the symbol table. -X sets the version
# package's build-time variable, surfaced via GET /health.
RUN LDFLAGS="-s -w -X 'github.com/OpenNSW/agency/backend/internal/version.version=${BUILD_VERSION}'" \
  && go build -ldflags="$LDFLAGS" -o /out/agency ./cmd/server \
  && go build -ldflags="$LDFLAGS" -o /out/migrate ./cmd/migrate \
  && go build -ldflags="$LDFLAGS" -o /out/nswac ./cmd/cli

# ---- Stage 3: runtime --------------------------------------------------------
FROM debian:bookworm-slim

LABEL org.opencontainers.image.source="https://github.com/OpenNSW/agency"
LABEL org.opencontainers.image.description="NSW Agency service (backend API + officer portal)"

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && useradd -u 1001 -r -s /bin/false -d /app appuser \
  && mkdir -p /app /app/web /data \
  && chown -R appuser:appuser /data /app

WORKDIR /app

# Go binaries
COPY --from=backend-builder --chown=appuser:appuser /out/agency /app/agency
COPY --from=backend-builder --chown=appuser:appuser /out/migrate /app/migrate
COPY --from=backend-builder /out/nswac /usr/local/bin/nswac
COPY --from=backend-builder --chown=appuser:appuser /app/migrations /app/migrations

# Task configs and forms are NOT baked into the image. They are fetched at
# runtime by the artifact loader from an external source (local mount, GitHub,
# or S3/R2), selected via ARTIFACT_LOADER_TYPE. See backend/.env.example.

# Built frontend, served (read-only) by the Go binary. The server resolves its
# asset dir as "web" relative to WORKDIR (/app), so it must land at /app/web.
# /runtime-env.js is generated dynamically from the environment, so nothing is
# written into this directory at runtime.
COPY --from=frontend-builder --chown=appuser:appuser /app/dist /app/web

# Runtime settings — UID 1001 matches appuser, OpenShift-compatible
USER appuser

# Single port serves both API and SPA (override via PORT env var)
EXPOSE 8081

# No ENTRYPOINT: the migrate Job reuses this image by overriding CMD with
# ["/app/migrate","up"]; the default runs the agency server.
CMD ["/app/agency"]
